export const SEARCH_SONG = "SEARCH_SONG";
export const GET_SONGS = "GET_SONGS";
export const EXPAND_COLLAPSE_SEARCH_BAR = "EXPAND_COLLAPSE_SEARCH_BAR";
export const PLAY_SONG = "PLAY_SONG";
export const PAUSE_SONG = "PAUSE_SONG";
