export const SEARCH_SONG = "SEARCH_SONG";
export const GET_SONGS = "GET_SONGS";
export const EXPAND_COLLAPSE_SEARCH_BAR = "EXPAND_COLLAPSE_SEARCH_BAR";
export const PLAY_SONG = "PLAY_SONG";
export const PAUSE_SONG = "PAUSE_SONG";
export const NEXT_SONG = "NEXT_SONG";
export const UPDATE_DURATION = "UPDATE_DURATION";
export const UPDATE_CURRENT_TIME = "UPDATE_CURRENT_TIME";
